In [2]:
import torch
#print(torch.__file__)


C:\Users\admin\AppData\Roaming\Python\Python36\site-packages\torch\__init__.py


## 1、RNN

In [5]:
#输入特征维度5，输出维度10, 层数2
rnn = torch.nn.RNN(5, 10, 2)
#rnn = torch.nn.RNN(5, 10, 2,bidirectional=True)
#seq长度4，batch_size=2
input = torch.randn(4 , 2 , 5)
h_0 =torch.randn(2 , 2 , 10)
output0,hn0=rnn(input ,h_0) 

print(output0.size(),hn0.size())
#>>torch.Size([4, 2, 10]) torch.Size([2, 2, 10])


torch.Size([4, 2, 10]) torch.Size([2, 2, 10])


In [6]:
[(para[0],para[1].shape) for para in list(rnn.named_parameters())]


[('weight_ih_l0', torch.Size([10, 5])),
 ('weight_hh_l0', torch.Size([10, 10])),
 ('bias_ih_l0', torch.Size([10])),
 ('bias_hh_l0', torch.Size([10])),
 ('weight_ih_l1', torch.Size([10, 10])),
 ('weight_hh_l1', torch.Size([10, 10])),
 ('bias_ih_l1', torch.Size([10])),
 ('bias_hh_l1', torch.Size([10]))]

In [7]:
rnn = torch.nn.RNN(5, 10, 2,bidirectional=True)
[(para[0],para[1].shape) for para in list(rnn.named_parameters())]

[('weight_ih_l0', torch.Size([10, 5])),
 ('weight_hh_l0', torch.Size([10, 10])),
 ('bias_ih_l0', torch.Size([10])),
 ('bias_hh_l0', torch.Size([10])),
 ('weight_ih_l0_reverse', torch.Size([10, 5])),
 ('weight_hh_l0_reverse', torch.Size([10, 10])),
 ('bias_ih_l0_reverse', torch.Size([10])),
 ('bias_hh_l0_reverse', torch.Size([10])),
 ('weight_ih_l1', torch.Size([10, 20])),
 ('weight_hh_l1', torch.Size([10, 10])),
 ('bias_ih_l1', torch.Size([10])),
 ('bias_hh_l1', torch.Size([10])),
 ('weight_ih_l1_reverse', torch.Size([10, 20])),
 ('weight_hh_l1_reverse', torch.Size([10, 10])),
 ('bias_ih_l1_reverse', torch.Size([10])),
 ('bias_hh_l1_reverse', torch.Size([10]))]

In [17]:
?torch.nn.GRU()

Init signature: torch.nn.GRU(*args, **kwargs)
Docstring:     
Applies a multi-layer gated recurrent unit (GRU) RNN to an input sequence.


For each element in the input sequence, each layer computes the following
function:

.. math::
    \begin{array}{ll}
        r_t = \sigma(W_{ir} x_t + b_{ir} + W_{hr} h_{(t-1)} + b_{hr}) \\
        z_t = \sigma(W_{iz} x_t + b_{iz} + W_{hz} h_{(t-1)} + b_{hz}) \\
        n_t = \tanh(W_{in} x_t + b_{in} + r_t * (W_{hn} h_{(t-1)}+ b_{hn})) \\
        h_t = (1 - z_t) * n_t + z_t * h_{(t-1)}
    \end{array}

where :math:`h_t` is the hidden state at time `t`, :math:`x_t` is the input
at time `t`, :math:`h_{(t-1)}` is the hidden state of the layer
at time `t-1` or the initial hidden state at time `0`, and :math:`r_t`,
:math:`z_t`, :math:`n_t` are the reset, update, and new gates, respectively.
:math:`\sigma` is the sigmoid function, and :math:`*` is the Hadamard product.

In a multilayer GRU, the input :math:`x^{(l)}_t` of the :math:`l` -th layer
(:math:`l

In [16]:
?torch.nn.LSTM()

Init signature: torch.nn.LSTM(*args, **kwargs)
Docstring:     
Applies a multi-layer long short-term memory (LSTM) RNN to an input
sequence.


For each element in the input sequence, each layer computes the following
function:

.. math::
    \begin{array}{ll} \\
        i_t = \sigma(W_{ii} x_t + b_{ii} + W_{hi} h_{t-1} + b_{hi}) \\
        f_t = \sigma(W_{if} x_t + b_{if} + W_{hf} h_{t-1} + b_{hf}) \\
        g_t = \tanh(W_{ig} x_t + b_{ig} + W_{hg} h_{t-1} + b_{hg}) \\
        o_t = \sigma(W_{io} x_t + b_{io} + W_{ho} h_{t-1} + b_{ho}) \\
        c_t = f_t \odot c_{t-1} + i_t \odot g_t \\
        h_t = o_t \odot \tanh(c_t) \\
    \end{array}

where :math:`h_t` is the hidden state at time `t`, :math:`c_t` is the cell
state at time `t`, :math:`x_t` is the input at time `t`, :math:`h_{t-1}`
is the hidden state of the layer at time `t-1` or the initial hidden
state at time `0`, and :math:`i_t`, :math:`f_t`, :math:`g_t`,
:math:`o_t` are the input, forget, cell, and output gates, respective

## 2、LSTM

In [14]:
lstm = torch.nn.LSTM(5, 10, 2, bidirectional=False)
lstm = torch.nn.LSTM(5, 10, 2, bidirectional=True)
#seq长度4，batch_size=2
input = torch.randn(4 , 2 , 5)
h_0 =torch.randn(2*2 , 2 , 10)
c_0 =torch.randn(2*2 , 2 , 10)
output1,(hn1,cn1)=lstm(input ,(h_0,c_0))
output1.shape,hn1.shape,cn1.shape

(torch.Size([4, 2, 20]), torch.Size([4, 2, 10]), torch.Size([4, 2, 10]))

In [6]:
lstm.parameters

<bound method Module.parameters of LSTM(5, 10, num_layers=2)>

In [7]:
[(para[0],para[1].shape) for para in list(lstm.named_parameters())]

[('weight_ih_l0', torch.Size([40, 5])),
 ('weight_hh_l0', torch.Size([40, 10])),
 ('bias_ih_l0', torch.Size([40])),
 ('bias_hh_l0', torch.Size([40])),
 ('weight_ih_l1', torch.Size([40, 10])),
 ('weight_hh_l1', torch.Size([40, 10])),
 ('bias_ih_l1', torch.Size([40])),
 ('bias_hh_l1', torch.Size([40]))]

## 3、GRU

In [8]:
gru = torch.nn.GRU(5,10,2)
input = torch.randn(4,2,5)
h_0 = torch.randn(2,2,10)
output2,h2= gru(input,h_0)
print(output2.shape,h2.shape)

torch.Size([4, 2, 10]) torch.Size([2, 2, 10])


In [10]:
hn0,hn1,h2

(tensor([[[ 0.6957,  0.6993, -0.3725, -0.2313, -0.6991,  0.4444,  0.5149,
            0.6077,  0.8198, -0.8009],
          [ 0.4669,  0.8639, -0.3396, -0.1665, -0.7004,  0.4820,  0.2837,
           -0.1118,  0.7474, -0.0715]],
 
         [[-0.1502,  0.4686, -0.2533,  0.6203,  0.7747,  0.5299, -0.1359,
            0.0369, -0.5976, -0.4017],
          [ 0.3929,  0.3828, -0.1115,  0.5295,  0.6983,  0.1508,  0.0953,
           -0.5248, -0.3344, -0.4349]]], grad_fn=<StackBackward0>),
 tensor([[[-0.0837, -0.0961, -0.1969,  0.0425, -0.0880,  0.0380,  0.1046,
           -0.0930, -0.0611, -0.0668],
          [-0.0377, -0.1121, -0.1301, -0.0113, -0.0489,  0.0365,  0.0101,
            0.0299,  0.0221,  0.0672]],
 
         [[ 0.0124,  0.1027,  0.0286,  0.1331, -0.0883,  0.1674, -0.0543,
            0.2114, -0.1614,  0.0054],
          [ 0.0532,  0.1649,  0.0051,  0.1305, -0.0198,  0.0602, -0.2208,
            0.1866, -0.2101, -0.0285]]], grad_fn=<StackBackward0>),
 tensor([[[-0.0899,  0.0427,  0.

In [14]:
cn1

tensor([[[-0.2196, -0.1863, -0.5052,  0.0954, -0.2868,  0.0638,  0.2701,
          -0.1932, -0.1768, -0.1228],
         [-0.0795, -0.2140, -0.3298, -0.0235, -0.1308,  0.0796,  0.0219,
           0.0893,  0.0603,  0.1613]],

        [[ 0.0305,  0.2051,  0.0602,  0.2996, -0.1438,  0.3860, -0.0891,
           0.4270, -0.3092,  0.0113],
         [ 0.1255,  0.3304,  0.0103,  0.2761, -0.0308,  0.1382, -0.3696,
           0.3601, -0.4045, -0.0607]]], grad_fn=<StackBackward0>)

In [10]:
[(para[0],para[1].shape) for para in list(gru.named_parameters())]

[('weight_ih_l0', torch.Size([30, 5])),
 ('weight_hh_l0', torch.Size([30, 10])),
 ('bias_ih_l0', torch.Size([30])),
 ('bias_hh_l0', torch.Size([30])),
 ('weight_ih_l1', torch.Size([30, 10])),
 ('weight_hh_l1', torch.Size([30, 10])),
 ('bias_ih_l1', torch.Size([30])),
 ('bias_hh_l1', torch.Size([30]))]